---
title: "Untitled"
author: "Margaret Janiczek"
date: "2023-05-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(corrplot)
```

## R Markdown

$logit[Pr(Y = 1| \mathbf{X}, Z] = \alpha + \beta^T\mathbf{X} + \gamma Z $

```{r}
dat1 <- readRDS("data2/dat1")

dat2 <- readRDS("data2/dat2")

dat3 <- readRDS("data2/dat3")

dat4 <- readRDS("data2/dat4")


```

Scenario 1

```{r}

M1 <- cor(dat1 %>%
  select(starts_with("X")))
corrplot(M1, method = "color", title = "Scenario 1", tl.pos = 'n')

dat1_long <- dat1 %>%
  select(y, starts_with("X")) %>%
  pivot_longer(-y, names_prefix = "X") 

dat1_long$name <- factor(dat1_long$name, levels = dat1_long$name)

dat1_long %>%
  group_by(y, name) %>%
  summarise(value = sum(value), .groups = 'drop') %>%
  ungroup() %>%
  arrange(y, as.numeric(name)) %>%
  mutate(
    associated = as.factor(rep(c(0, 0, 0, 1, 0, 1, 0, 1, 1, 1
                     , rep(0, 40)),2))
  ) %>%
  ggplot(aes(name, value, fill = associated)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~y) +
  theme_minimal()+ 
  theme(axis.text.x=element_blank()) +
  ggtitle("Scenario 1 - split by outcome")
  
```

Scenario 2

```{r}

M2 <- cor(dat2 %>%
  select(starts_with("X")))
corrplot(M2, method = "color",  title = "Scenario 2", tl.pos = 'n')

dat2_long <- dat4 %>%
  select(y, starts_with("X")) %>%
  pivot_longer(-y, names_prefix = "X") 


dat2_long %>%
  group_by(y, name) %>%
  summarise(value = sum(value), .groups = 'drop') %>%
  ungroup() %>%
  arrange(y, as.numeric(name)) %>%
  mutate(
    associated = as.factor(rep(c(0, 0, 0, 1, 0, 1, 0, 1, 1, 1
                     , rep(0, 40)),2))
  ) %>%
  ggplot(aes(name, value, fill = associated)) +
  geom_bar(stat = "identity") +
  facet_wrap(~y) +
  theme_minimal() + 
  theme(axis.text.x=element_blank()) +
  ggtitle("Scenario 4")
```

Scenario 3

```{r}

M3 <- cor(dat3 %>%
  select(starts_with("X")))
corrplot(M3, method = "color", title = "Scenario 3", tl.pos = 'n')
```

Scenario 4

```{r}

library(corrplot)
M <- cor(dat4 %>%
  select(starts_with("X")))
corrplot(M, method = "color",  title = "Scenario 4", tl.pos = 'n')
```


